/*
 * BrainRex API
 *
 * The Brainrex API is a collection of analytics tools and data integrations made for blockchain developers. In particular we offer Natural Language Processing and Anomaly detection algorithms that have been fine tune to understand text data and time series in the domain speficic setting of cryptocurrency and blockchain technology. This technology is intended to be use as building blocks to bigger applications, we offer examples on how to use them for Trading Backtesting and Smart Contract anomaly monitoring.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package brainrex

type CandleRequest struct {
	// Name of the currency pair
	BaseTradingSymbol string `json:"base_trading_symbol,omitempty"`
	// Name of the exchange
	Exchange string `json:"exchange,omitempty"`
	// Name of the market
	Interval string `json:"interval,omitempty"`
	// Name of the data format availables (standard)
	QuoteTradingSymbol string `json:"quote_trading_symbol,omitempty"`
}
