/*
 * BrainRex API
 *
 * The Brainrex API is a collection of analytics tools and data integrations made for blockchain developers. In particular we offer Natural Language Processing and Anomaly detection algorithms that have been fine tune to understand text data and time series in the domain speficic setting of cryptocurrency and blockchain technology. This technology is intended to be use as building blocks to bigger applications, we offer examples on how to use them for Trading Backtesting and Smart Contract anomaly monitoring.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package brainrex

type TickerResponseInner struct {
	// Closing price quote of the time frame with two decimal points
	LastUpdated string `json:"lastUpdated,omitempty"`
	// Highest price of the time frame with two decimal points
	Name string `json:"name,omitempty"`
	// Percetange change in the last 24 hours
	PercentChange24hUsd float32 `json:"percentChange24hUsd,omitempty"`
	// Opening price quote of the time frame with two decimal points
	PriceBtc float32 `json:"priceBtc,omitempty"`
	// Timestamp of the beggining of the frame
	PriceUsd float32 `json:"priceUsd,omitempty"`
	// Volume of currency exchanged in the time frame with two decimal points
	Symbol string `json:"symbol,omitempty"`
}
