/*
 * BrainRex API
 *
 * The Brainrex API is a collection of analytics tools and data integrations made for blockchain developers. In particular we offer Natural Language Processing and Anomaly detection algorithms that have been fine tune to understand text data and time series in the domain speficic setting of cryptocurrency and blockchain technology. This technology is intended to be use as building blocks to bigger applications, we offer examples on how to use them for Trading Backtesting and Smart Contract anomaly monitoring.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package brainrex

type Ohclv struct {
	// Closing price quote of the time frame with two decimal points
	Close float32 `json:"close,omitempty"`
	// Highest price of the time frame with two decimal points
	High float32 `json:"high,omitempty"`
	// End date in YYYY/MM/DD
	EndDate string `json:"end_date,omitempty"`
	// Opening price quote of the time frame with two decimal points
	Open float32 `json:"open,omitempty"`
	// Timestamp of the beggining of the frame
	Time string `json:"time,omitempty"`
	// Volume of currency exchanged in the time frame with two decimal points
	Volume float32 `json:"volume,omitempty"`
	// Volume of currency exchanged in dollars the time frame with two decimal points
	UsdVolume float32 `json:"usdVolume,omitempty"`
	// Volume of currency exchanged in dollars the time frame with two decimal points
	BtcVolume float32 `json:"btcVolume,omitempty"`
	// Volume of currency exchanged in dollars the time frame with two decimal points
	QuoteVolume float32 `json:"quoteVolume,omitempty"`
}
